package com.Adactin_Hotel_App;

import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import org.apache.log4j.Logger;

import org.apache.commons.io.FileUtils;
import org.apache.log4j.PropertyConfigurator;
import org.apache.poi.xslf.model.PropertyFetcher;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import com.pom.Book_Now;
import com.pom.Booking_Confirmation;
import com.pom.Login_Page;
import com.pom.Search_Hotel;
import com.pom.Verify_Booking;
import com.pomanager.Page_Object_Manager;

public class RunnerClass extends BaseClass {
	public static WebDriver driver = getBrowser("chrome");
	public static Page_Object_Manager pom=new Page_Object_Manager(driver);
	public static Logger log=Logger.getLogger(RunnerClass.class);
	public static void main(String[] args) throws Throwable {
		PropertyConfigurator.configure("log4j.properties");
		url("https://adactinhotelapp.com/");
		log.info("Browser Launched-Adactin");
		String username = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 11, 5);
		inputValueElement(pom.setInstanceLp().getUsername(), username);
		String password = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 12, 5);
		inputValueElement(pom.setInstanceLp().getPassword(), password);
		clickOnElement(pom.setInstanceLp().getLogin());
		log.info("Data collected from spread sheet and Logged in");
		implicitwait(10, TimeUnit.SECONDS);
		String location = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 14, 5);
		dropdown("index", pom.setInstanceSh().getLocation(), location);
		String hotel = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 15, 5);
		dropdown("text", pom.setInstanceSh().getHotels(), hotel);
		String rtype = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 16, 5);
		dropdown("value", pom.setInstanceSh().getrType(), rtype);
		String rono = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 17, 5);
		dropdown("index", pom.setInstanceSh().getRnos(), rono);
		pom.setInstanceSh().getInDate().clear();
		String ckInDate = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 18, 5);
		inputValueElement(pom.setInstanceSh().getInDate(), ckInDate);
		pom.setInstanceSh().getOutDate().clear();
		String ckOutDate = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 19, 5);
		inputValueElement(pom.setInstanceSh().getOutDate(), ckOutDate);
		implicitwait(5, TimeUnit.SECONDS);
		String aroom = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 20, 5);
		dropdown("index", pom.setInstanceSh().getAdultRoom(), aroom);
		String croom = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 21, 5);
		dropdown("index",pom.setInstanceSh().getChildRoom(), croom);
		clickOnElement(pom.setInstanceSh().getSubmt());
		log.info("Data retrived from excel file and Successfully Room Selected");
		clickOnElement(pom.setInstanceVb().getSelectHotel());
		clickOnElement(pom.setInstanceVb().getCont());
		implicitwait(5, TimeUnit.SECONDS);
		String firstName = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 25, 5);
		inputValueElement(pom.setInstanceBn().getfName(), firstName);
		String lastName = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 27, 5);
		inputValueElement(pom.setInstanceBn().getlName(), lastName);
		String address = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 28, 5);
		inputValueElement(pom.setInstanceBn().getAddress(), address);
		String ccNos = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 29, 5);
		inputValueElement(pom.setInstanceBn().getCcNo(), ccNos);
		String ctype = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 30, 5);
		dropdown("index", pom.setInstanceBn().getCcType(), ctype);
		String month = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 31, 5);
		dropdown("index",pom.setInstanceBn().getExpMonth(), month);
		String year = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 32, 5);
		dropdown("index",pom.setInstanceBn().getCcExpYear(), year);
		String cvvno = particular_Data("D:\\QA Testing\\Project Session\\Test Cases.xlsx", 33, 5);
		inputValueElement(pom.setInstanceBn().getCvv(), cvvno);
		clickOnElement(pom.setInstanceBn().getBookNow());
		log.info("Datas received from excel file and Successfully Booked the rooms");
		takesscreenshot("C:\\Users\\Ramachandran\\eclipse-workspace\\Adactin_Hotel_App\\Screenshot\\BookingConf1.png");
		implicitwait(10, TimeUnit.SECONDS);
		scroll("scrollBy", "window.scrollBy(0,500);", null);
		clickOnElement(pom.setInstanceBc().getLogOut());
		log.info("Successfully logout");
	}
}
